
# [target.x86_64-unknown-linux-gnu]
# dockerfile = "./app-hyper/Dockerfile.x86_64"

# [target.aarch64-unknown-linux-gnu]
# dockerfile = "./app-hyper/Dockerfile.aarch64"

[build.dockerfile]
file = "./Dockerfile" # the dockerfile to use relative to the `Cargo.toml`
context = "."         # the context folder to build the script in. defaults to `.`
