[package]
name = "cor"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["rlib"]

[dependencies]
async-trait.workspace = true
tokio.workspace = true
thiserror.workspace = true
futures.workspace = true
