#![allow(missing_docs)]
mod server;
// mod service_api_v1;
// pub mod router;
// use clap::Parser;
use env_logger::Env;

/// Create custom server, wire it to the autogenerated router,
/// and pass it to the web server.
#[tokio::main(flavor = "multi_thread", worker_threads = 8)]
async fn main() {
let env = Env::default()
        .filter_or("LOG_LEVEL", "info")
        .write_style_or("LOG_STYLE", "auto");
    env_logger::init_from_env(env);

    // let addr = "127.0.0.1:8080";
    let addr = "0.0.0.0:8080";

    server::create(addr).await;
}
