[package]
name = "stubs"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["rlib"]

[dependencies]
common = { path = "../common" }

async-trait = "0.1.24"
# tokio = { version = "1.42", features = ["full"] }
