[package]
name = "biz_logic"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["rlib"]

[dependencies]
common = { path = "../common" }
biz_common = { path = "../biz-common" }
cor = { path = "../lib-cor" }
async-trait.workspace = true
tokio.workspace = true
