[package]
name = "common"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["rlib"]

[dependencies]
# async-trait = "0.1.24"
lazy_static = "1.5"
# tokio = { version = "1.42", features = ["full"] }
