openapi: 3.0.3
info:
  title: 'Marketplace Ads service ${VERSION_APP}'
  description: 'Marketplace a place where sellers and buyers meat each other. Ads service provides ads handling from 
    both sellers and buyers'
  license:
    #    identifier: Apache-2.0
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:8080/
tags:
  - name: swagger
    description: Свагер
  - name: ad
    description: Объявление (о покупке или продаже)
paths:
  /:
    get:
      tags:
        - swagger
      summary: Swagger
      operationId: swagger
      responses:
        200:
          description: Success
          content:
            text/html:
              schema:
                type: string
              example: 'whoa!'
