# This is a basic workflow to help you get started with Actions

name: 'CI-publish-AMD'

# Controls when the workflow will run
on:
  release:
    types: [ created ]
#  push:
#    branches:
#      - 'release/*'
  pull_request:
    branches:
      - 'release/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish-amd64:
    runs-on: ubuntu-24.04
    # runs-on: ubuntu-24.04-arm
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: davidB/rust-cargo-make@v1
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.CONTAINER_REGISTRY_HOST }}
          username: ${{ secrets.CONTAINER_REGISTRY_USER }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASS }}
  
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run tests
        run: cargo make push_all_amd64
        env:
          CONTAINER_REGISTRY_PREF: ${{ vars.CONTAINER_REGISTRY_PREF }}
          PROJECT_VERSION: ${{ github.event.release.tag_name }}
